runtime: custom

service: golang


env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  name: gnp-datapullsinautos-qa
  subnetwork_name: gnp-datapullsinautos-qa
  instance_tag: datapull-network